sudo: required
language: go
go:
  - 1.6

env:
  - PLATFORM=android-arm
  - PLATFORM=android-x64
  - PLATFORM=android-x86
  - PLATFORM=darwin-x64
  - PLATFORM=linux-arm
  - PLATFORM=linux-armv7
  - PLATFORM=linux-arm64
  - PLATFORM=linux-x64
  - PLATFORM=linux-x86
  - PLATFORM=windows-x64
  - PLATFORM=windows-x86
  - PLATFORM=all

services:
  - docker

before_install:
  - |
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ -n "${TRAVIS_TAG}" ] && [ "${PLATFORM}" = "all" ]; then
      make pull-all
    elif [ "${PLATFORM}" != "all" ]; then
      make pull
    fi

install:
  - go get -d ./...
  - go get -d github.com/scakemyer/libtorrent-go

script:
  - |
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ -n "${TRAVIS_TAG}" ] && [ "${PLATFORM}" = "all" ]; then
      make libs
    elif [ "${PLATFORM}" != "all" ]; then
      make libs
    fi
  - |
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ -n "${TRAVIS_TAG}" ] && [ "${PLATFORM}" = "all" ]; then
      make $PLATFORM
    elif [ "${PLATFORM}" != "all" ]; then
      make $PLATFORM
    fi
  - |
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ -n "${TRAVIS_TAG}" ] && [ "${PLATFORM}" = "all" ]; then
      # Push binaries to quasar-binaries repo
      make binaries
      cd binaries && git remote add binaries https://$GH_TOKEN@github.com/scakemyer/quasar-binaries
      git push binaries master
    fi
